name: CI
on:
  - pull_request
  - push

jobs:
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - uses: actions/checkout@v6

      - name: Build image for x86_64 with BIOS mode and without GPT
        run: |
          sudo ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 2G \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-bios-$(date +%Y-%m-%d).qcow2 -- ./example/configure.sh
      - name: Upload BIOS image (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: alpine-bios-x86_64
          path: alpine-bios-*.qcow2

      - name: Build image for x86_64 with BIOS mode and GPT
        run: |
          sudo ./alpine-make-vm-image \
              --image-format raw \
              --image-size 2G \
              --partition \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-bios-part-$(date +%Y-%m-%d).raw -- ./example/configure.sh
      # (Optional) Upload raw image if needed
      - name: Upload BIOS+GPT raw image (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: alpine-bios-gpt-x86_64
          path: alpine-bios-part-*.raw

      - name: Build image for x86_64 with UEFI mode
        run: |
          sudo ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 2G \
              --boot-mode UEFI \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-uefi-$(date +%Y-%m-%d).qcow2 -- ./example/configure.sh
      - name: Upload UEFI image (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: alpine-uefi-x86_64
          path: alpine-uefi-*.qcow2

      - name: Install qemu-aarch64 and register in binfmt
        uses: jirutka/setup-alpine@v1
        with:
          arch: aarch64

      - name: Build image for aarch64
        run: |
          sudo ./alpine-make-vm-image \
              --arch aarch64 \
              --image-format qcow2 \
              --image-size 2G \
              --repositories-file example/repositories \
              --packages "$(cat example/packages) linux-virt@edge" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-aarch64-$(date +%Y-%m-%d).qcow2 -- ./example/configure.sh
      - name: Upload aarch64 image (UEFI‑ready but may need extra boot setup)
        uses: actions/upload-artifact@v4
        with:
          name: alpine-aarch64
          path: alpine-aarch64-*.qcow2

  test-alpine:
    name: Test on Alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: sudo modprobe nbd max_part=16

      - name: Set up Alpine Linux v3.22
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.22

      - name: Build image for x86_64 with BIOS mode and without GPT
        run: |
          ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 2G \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-bios-$(date +%Y-%m-%d).qcow2 -- ./example/configure.sh
        shell: alpine.sh --root {0}
      - name: Upload BIOS image (x86_64) [Alpine runner]
        uses: actions/upload-artifact@v4
        with:
          name: alpine-bios-x86_64-alpine
          path: alpine-bios-*.qcow2

      - name: Build image for x86_64 with UEFI mode
        run: |
          ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 2G \
              --boot-mode UEFI \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-uefi-$(date +%Y-%m-%d).qcow2 -- ./example/configure.sh
        shell: alpine.sh --root {0}
      - name: Upload UEFI image (x86_64) [Alpine runner]
        uses: actions/upload-artifact@v4
        with:
          name: alpine-uefi-x86_64-alpine
          path: alpine-uefi-*.qcow2

      - name: Install qemu-aarch64 and register in binfmt
        uses: jirutka/setup-alpine@v1
        with:
          arch: aarch64
          shell-name: alpine-aarch64.sh

      - name: Build image for aarch64
        run: |
          ./alpine-make-vm-image \
              --arch aarch64 \
              --branch edge \
              --image-format qcow2 \
              --image-size 2G \
              --packages "$(cat example/packages)" \
              --fs-skel-dir example/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              alpine-aarch64-$(date +%Y-%m-%d).qcow2 -- ./example/configure.sh
        shell: alpine.sh --root {0}
      - name: Upload aarch64 image [Alpine runner]
        uses: actions/upload-artifact@v4
        with:
          name: alpine-aarch64-alpine
          path: alpine-aarch64-*.qcow2
